
###############  State constraints  #############################################
max_steer: 0.78         # Maximal and (- minimal) steering angle [rad]
max_speed: 1.0              # Maximal speed [m/s]       --- Not quite used yet
min_speed: -1.0             # Minimal speed [m/s]       --- Not quite used yet
max_acc: 0.1                # Max acceleration [m/ss]
min_acc: -0.1               # Min acceleration [m/ss]


###############  Mechanical properties  #############################################
width: 0.05                  # Width of the track of the vehicle [m]
L: 0.098                      # Wheel base [m]
Lr: 0.051                  # (m) Distance from rear axle to center of mass ------------- TO BE IDENTIFIED -------------
Cf: 800.0                   # Front tire stiffness coefficient
Cr: 800.0                   # Rear tire stiffness coefficient
Iz: 0.00019863              # Vehicle moment of inertia     --- To be identified
m: 0.144                    # Vehicle mass


################  Friction coefficients  ############################################
c_a: 0.8                   # Drag coefficient
c_r1: 0.1                  # Friction coefficient
model_type: 'linear'        # Function used for state prediction ('linear'/'nonlinear')