CBF_robotarium:
  max_steer: 0.523599
  max_speed: 6
  min_speed: -1.0
  safety_radius: 7
  barrier_gain: 0.05
  magnitude_limit: 6
CBF_simple:
  max_steer: 0.785398
  max_acc: 100
  min_acc: -100
  safety_radius: 2
  barrier_gain: 0.01
  arena_gain: 0.01
  Kv: 0.1
C3BF:
  max_steer: 0.785398
  max_acc: 5
  min_acc: -5
  safety_radius: 1.5
  barrier_gain: 1
  arena_gain: 50
  Kv: 0.1
DWA:
  a_resolution: 0.05
  v_resolution: 0.05
  delta_resolution: 5
  to_goal_cost_gain: 1
  speed_cost_gain: 1
  obstacle_cost_gain: 2
  heading_cost_gain: 1
  dilation_factor: 0.1
LBP:
  max_steer: 0.785398
  max_speed: 2
  min_speed: -1.0
  max_acc: 5
  min_acc: -5
  a_resolution: 0.5
  v_resolution: 0.5
  delta_resolution: 15
  predict_time: 1.5
  to_goal_cost_gain: 20
  speed_cost_gain: 1
  obstacle_cost_gain: 30
  heading_cost_gain: 1
  robot_stuck_flag_cons: 0.001
  dilation_factor: 0.35
MPC:
  max_steer: 0.785398
  max_speed: 2
  min_speed: -1.0
  max_acc: 2
  min_acc: -2
  horizon: 8
  dt_pred: 0.2
  safety_radius: 2
Controller:
  dt: 0.01    # This needs to either be dynamized or fixed
  ph: 0.3
  # controller_type: MPC
  # cbf_type: C3BF
  # safety: 10
  # add_noise: false
  # noise_scale: 0.4
robot_num: 5
min_dist: 3
width: 10
height: 10
timer_freq: 0.01
plot_traj: false
to_goal_stop_distance: 2.5
show_animation: true
