CBF:                              ### Collision Barrier Functions
  safety_radius: 0.2              # [m] Radius of each barrier function
  barrier_gain: 10000.0           # [-] Gain of barrier function
  Kv: 0.2                         # [-] Gain of the barrier depending on car's velocity
C3BF:                             ### Collision Cone Control Barrier Functions      
  safety_radius: 0.2              # [m] Radius of each barrier function
  barrier_gain: 10000.0           # [-] Gain of barrier function
  Kv: 0.2                         # [-] Gain of the barrier depending on car's velocity
DWA:                              ### Dynamic Window Approach             
  a_resolution: 0.05              # [m/s^2] Resolution for the sampled acceleration
  v_resolution: 0.05              # [m/s] Resolution for the sampled velocity
  delta_samples: 20               # [-] Number of samples for the steering angle
  emergency_brake_distance: 5     # [-] Number of old trajectory left to trigger emergency brake
  to_goal_cost_gain: 1            # [-] Gain for the cost to the goal
  obstacle_cost_gain: 2           # [-] Gain for the cost to the obstacle
  dilation_factor: 2.0            # [-] Number of car's width to consider for collision
LBP:                            
  a_resolution: 0.05
  v_resolution: 0.05
  delta_samples: 20
  to_goal_cost_gain: 1            # [-] Gain for the cost to the goal
  obstacle_cost_gain: 2           # [-] Gain for the cost to the obstacle
  dilation_factor: 2.0            # [-] Number of car's width to consider for collision
# MPC:
#   max_steer: 0.785398
#   max_speed: 2
#   min_speed: -1.0
#   max_acc: 2
#   min_acc: -2
#   horizon: 8
#   dt_pred: 0.2
#   safety_radius: 2
Controller:                       ### Controller parameters        
  dt: 0.02                        # [s] Controller time step (both for control and traj_generation)
  ph: 0.5                         # [s] Prediction horizon
Simulation:                       ### Simulation parameters
  width: 4.5                      # [m] Width of the driving area    
  height: 3.5                     # [m] Height of the driving area        
  off_x: 0.5                      # [m] X offset for the driving area
  off_y: 1.25                     # [m] Y offset for the driving area
