CBF:
  safety_radius: 0.1
  barrier_gain: 7.0
  arena_gain: 7.0
  Kv: 0.2
C3BF:
  safety_radius: 0.1
  barrier_gain: 7.0
  arena_gain: 0.5
  Kv: 0.2
DWA:
  a_resolution: 0.01
  v_resolution: 0.01
  delta_resolution: 5
  to_goal_cost_gain: 1
  speed_cost_gain: 1
  obstacle_cost_gain: 2
  heading_cost_gain: 1
  dilation_factor: 0.1
LBP:
  a_resolution: 0.05
  v_resolution: 0.05
  delta_resolution: 5
  to_goal_cost_gain: 20
  speed_cost_gain: 1
  obstacle_cost_gain: 30
  heading_cost_gain: 1
  dilation_factor: 0.35
MPC:
  max_steer: 0.785398
  max_speed: 2
  min_speed: -1.0
  max_acc: 2
  min_acc: -2
  horizon: 8
  dt_pred: 0.2
  safety_radius: 2
Controller:
  dt: 0.1   
  ph: 0.5
  # controller_type: MPC
  # cbf_type: C3BF
  # safety: 10
  add_noise: false
  noise_scale: 0.4
Simulation:
  width: 4.3
  height: 3.3
  show_animation: true
